---
# handlers file for beats
- name: "update supervisord"
  shell: "supervisorctl reread && supervisorctl update"
  become: yes

- name: "restart beat"
  supervisorctl: name={{ beat }} state=restarted
